---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-supporterino-de-v1alpha1-piholecluster
  failurePolicy: Fail
  name: mpiholecluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - supporterino.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - piholeclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-supporterino-de-v1alpha1-piholecluster
  failurePolicy: Fail
  name: vpiholecluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - supporterino.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - piholeclusters
  sideEffects: None
