---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - supporterino.de
  resources:
  - piholeclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - supporterino.de
  resources:
  - piholeclusters/finalizers
  verbs:
  - update
- apiGroups:
  - supporterino.de
  resources:
  - piholeclusters/status
  verbs:
  - get
  - patch
  - update
