apiVersion: supporterino.de/v1alpha1
kind: PiHoleCluster
metadata:
  labels:
    app.kubernetes.io/name: pi-hole-operator
    app.kubernetes.io/managed-by: kustomize
  name: piholecluster-sample
spec:
  name: primary
  replicas: 2
  sync:
    cron: 0 0 * * *
  monitoring:
    exporter:
      enabled: true
  config:
    apiPassword:
      password: 123456abc
